### ISSUE TITLE
Bastion Service or Bastion VM support

### ISSUE THREAD

**Issue by lfeldman** [oracle-devrel/terraform-oci-cloudbricks-postgresql#7]
In this repo, we cannot use OCI BastionService/BastionVM to access PostgreSQL VMs in private subnet from the public Internet. If it is possible please consider adding BastionService and BastionVM support as options.

**Comment by dralquinta** [comment]
In current conditions, you can connect to the instances using a Jump Server on a subnet that has public access and then connectivity to the subnets without issues. As for bastion service indeed, the module doesn't have support for the plugin now, but it can be added. I'll work on that.

We don't plan to add coupled components beyond what's declared in the module, as the intention of this framework is to decouple all components as much as possible to prevent stiffness.

**Comment by dralquinta** [comment]
Functionality has been added, by adding an optional variable `bastion_service_enabled` defaulted to true. This adds the following code snippet as shown on registry: 

```shell
  dynamic "agent_config" {
    for_each = var.bastion_service_enabled ? [1] : []
    content {
      are_all_plugins_disabled = false
      is_management_disabled   = false
      is_monitoring_disabled   = false
      plugins_config {
        desired_state = "ENABLED"
        name          = "Bastion"
      }
    }
  }
```

Kindly confirm that this is the functionality change requested, to proceed with regression testing. 

Thanks!

**Comment by lfeldman** [comment]
I believe we should also add the bastion-session's part as you can see [here](https://github.com/oracle-devrel/terraform-oci-arch-postgresql/blob/main/bastion.tf):

```
resource "oci_bastion_session" "ssh_postgresql_master_session" {
  depends_on = [oci_core_instance.postgresql_master,
    oci_core_nat_gateway.postgresql_nat,
    oci_core_route_table.postgresql_rt2
  ]
  bastion_id = oci_bastion_bastion.bastion-service[0].id
  key_details {
    public_key_content = tls_private_key.public_private_key_pair.public_key_openssh
  }
  target_resource_details {
    session_type       = "MANAGED_SSH"
    target_resource_id = oci_core_instance.postgresql_master.id
    target_resource_operating_system_user_name = "opc"
    target_resource_port                       = 22
    target_resource_private_ip_address         = oci_core_instance.postgresql_master.private_ip
  }

  display_name           = "ssh_postgresql_master_session"
  key_type               = "PUB"
  session_ttl_in_seconds = 10800
}
```

**Comment by dralquinta** [comment]
I'll review this functionality in more detail, as the current framework does not require bastion_service enablement given all execution is via null resource. Only use case I see is for accessing this, that can currently be done by a bastion server which is offers more flexibility for staging server functionalities.

**Comment by dralquinta** [comment]
After considering the change, this will not be included on module, as there is no real functionality expected for bastion service inside the same decoupled component. As for modularity, the bastion service along with the pertaining sessions will be decoupled on separate brick under https://github.com/oracle-devrel/terraform-oci-cloudbricks-bastionservice

**Comment by lfeldman** [comment]
Ok. I am not pushing for change, but it is worth considering that Bastion Session is tightly coupled with compute instance when SSH-managed connection needs to be established. On the other hand, Bastion Session has a dependency on Bastion Service resources. I am not entirely sure how you would like to inject Bastion Sessions and Bastion Service into the PostgreSQL module. It looks like a chicken-egg problem to me. Our approach seems to be valid. Bastion Service should be injected into the PostgreSQL module, and then inside the module, VMs + corresponding Bastion Sessions are created and associated with injected Service.

**Comment by dralquinta** [comment]
Bastion Service is today just another way of accessing resources. A Jump Server with managed SSH keys will do the same, plus being more flexible in what you can do with it. You can rollout a full staging server in front of the infrastructure and not only use it for SSH Jumping. Today, Bastion Service is not something mandatory for this module in particular, so there is no strong reason to add it in the short term. However as you say the agent support needs to be enabled in computes is a must to use the service in the first place, so that will be included in forthcoming releases once the dependant module is done.
