### ISSUE TITLE
Option to inject VCN/subnet or create VCN/subnet inside the module

### ISSUE THREAD

**Issue by lfeldman** [oracle-devrel/terraform-oci-cloudbricks-postgresql#8]
Please consider adding an option for creating VCN/subnet inside the module as an alternative to injecting VCN/subnet from outside. It also should include both fully private (with DRG) and fully public scenarios.

**Comment by dralquinta** [comment]
Thanks for reporting this. 

The asset created is part of a larger framework that makes extensive use of reusable components. VCN, and all network artifacts are decoupled from this as this stiffens the rollout of more flexible components. For such reason, this module won't offer VCN support in the foreseeable future as it'll go against the flexibility spirit of the framework.

**Comment by lfeldman** [comment]
Our [module](https://github.com/oracle-devrel/terraform-oci-arch-postgresql/tree/main/examples) work differently. We have the option to use externally injected infra or infra can be deployed inside the module. It looks like here lays the difference between our frameworks.

**Comment by dralquinta** [comment]
The module you comment is more of an enclosed solution with the chance of injecting an external networking infrastructure, as of this one offers a completely decoupled delivery that allows this to integrate this upwards using variable and module overloading anyway you need it. Indeed modules are different as the spirit of this framework is achieving the DRY principle as much as possible.
